fileWallet:
  path: "/tmp"
  disableListener: true
  filenames:
    primaryExt: ".toml"
  metadata:
    format: auto
    keyFileProperty: '{{ index .signing "key-file" }}'
    passwordFileProperty: '{{ index .signing "password-file" }}'
backend:
  chainId: 123456789
server:
  port: 8545
  address: 0.0.0.0
